#FROM gcr.io/tensorflow/tensorflow 
FROM tensorflow/tensorflow 
#FROM tensorflow/tensorflow:latest-gpu
RUN apt-get update -y;apt-get install -y vim python-tk
#RUN pip install opencv-python
WORKDIR /app
